export const NOTIFICATION_TYPE = {
  APPOINTMENT: "APPOINTMENT",
  RECURRING_APPOINTMENT: "RECURRING_APPOINTMENT",
  REVIEW: "REVIEW",
  REVIEW_REPLY: "REVIEW_REPLY",
  REVIEW_LIKE: "REVIEW_LIKE",
  REVIEW_REPORT: "REVIEW_REPORT",
  CREATE_INVOICE: "CREATE_INVOICE",
};
