image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: "/certs"

build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

deploy:
  stage: deploy
  before_script:
    - "command -v ssh-agent >/dev/null || ( apk add --update openssh )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - ssh $VPS_USER@$VPS_HOST "docker ps -a"
    - ssh $VPS_USER@$VPS_HOST "docker stop tro-server || true && docker rm tro-server || true"
    - |
      ssh $VPS_USER@$VPS_HOST "docker run -d --name tro-server -p 8891:8891 \
        $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  only:
    - dev

        # -e USE_REDIS_CACHE=${USE_REDIS_CACHE} \
      # -e DATABASE_URL=${DATABASE_URL} \
        # -e REDIS_HOST=${REDIS_HOST} \
        # -e REDIS_PORT=${REDIS_PORT} \
        # -e REDIS_CACHE_EXPIRATION=${REDIS_CACHE_EXPIRATION} \
        # -e REDIS_PASSWORD=${REDIS_PASSWORD} \
        #         -e APP_NAME=${APP_NAME} \
        # -e PORT=8891 \
        # -e CLOUDINARY_KEY=${CLOUDINARY_KEY} \
        # -e CLOUDINARY_SECRET=${CLOUDINARY_SECRET} \
        # -e CLOUDINARY_NAME=${CLOUDINARY_NAME} \
        # -e SECRET_KEY=${SECRET_KEY} \
        # -e SECRET_REFRESH_TOKEN_KEY=${SECRET_REFRESH_TOKEN_KEY} \
        # -e MAIL_MAILER=${MAIL_MAILER} \
        # -e MAIL_HOST=${MAIL_HOST} \
        # -e MAIL_PORT=${MAIL_PORT} \
        # -e MAIL_USERNAME=${MAIL_USERNAME} \
        # -e MAIL_PASSWORD=${MAIL_PASSWORD} \
        # -e MAIL_ENCRYPTION=${MAIL_ENCRYPTION} \
        # -e MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS} \
        # -e MAIL_FROM_NAME=${MAIL_FROM_NAME} \
        # -e MOMO_ACCESS_KEY=${MOMO_ACCESS_KEY} \
        # -e MOMO_SECRET_KEY=${MOMO_SECRET_KEY} \
        # -e PHONE_API_KEY=${PHONE_API_KEY} \
        # -e CLIENT_ID=${CLIENT_ID} \
        # -e CLIENT_SECRET=${CLIENT_SECRET} \
        # -e AZURE_COMPUTER_VISION_API_KEY=${AZURE_COMPUTER_VISION_API_KEY} \
        # -e AZURE_COMPUTER_VISION_ENDPOINT=${AZURE_COMPUTER_VISION_ENDPOINT} \